
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma", // Schema location - Your DB models will live here
  migrations: {
    path: "prisma/migrations", // Migration files location - Prisma will store DB changes here
  },
  engine: "classic", // Engine type - classic or library
  datasource: {
    url: env("DATABASE_URL"), // Database URL - Your DB connection string
  },
});
